INSERT INTO `saas_shop_goods_spec` (`spec_id`, `site_id`, `goods_id`, `spec_name`, `spec_values`) VALUES (1, 0, 20, '份量', '6英寸,8英寸');
INSERT INTO `saas_shop_goods_spec` (`spec_id`, `site_id`, `goods_id`, `spec_name`, `spec_values`) VALUES (2, 0, 20, '奶油品质', '淡乳脂奶油,安佳动物奶油');
INSERT INTO `saas_shop_goods_spec` (`spec_id`, `site_id`, `goods_id`, `spec_name`, `spec_values`) VALUES (3, 0, 20, '夹心选择', '新鲜芒果肉 ,红心火龙果,奥利奥饼干碎');
INSERT INTO `saas_shop_goods_spec` (`spec_id`, `site_id`, `goods_id`, `spec_name`, `spec_values`) VALUES (4, 0, 32, '口味', '麻辣味,泡椒味,孜然味,藤椒味');
INSERT INTO `saas_shop_goods_spec` (`spec_id`, `site_id`, `goods_id`, `spec_name`, `spec_values`) VALUES (5, 0, 33, '口味', '五香口味');
INSERT INTO `saas_shop_goods_spec` (`spec_id`, `site_id`, `goods_id`, `spec_name`, `spec_values`) VALUES (6, 0, 34, '口味', '五香味76g*2袋,麻辣味76g*2袋,五香76g*2袋+麻辣76g*2袋,五香味76g*4袋,麻辣味76g*4袋,麻辣味250g*1袋,五香味250g*1袋');
INSERT INTO `saas_shop_goods_spec` (`spec_id`, `site_id`, `goods_id`, `spec_name`, `spec_values`) VALUES (7, 0, 35, '口味', '五香口味');
INSERT INTO `saas_shop_goods_spec` (`spec_id`, `site_id`, `goods_id`, `spec_name`, `spec_values`) VALUES (8, 0, 36, '口味', '五香味76g*2袋,麻辣味76g*2袋,五香76g*2袋+麻辣76g*2袋,五香味76g*4袋,麻辣味76g*4袋,麻辣味250g*1袋,五香味250g*1袋');
INSERT INTO `saas_shop_goods_spec` (`spec_id`, `site_id`, `goods_id`, `spec_name`, `spec_values`) VALUES (9, 0, 37, '口味', '咖喱味,麻辣味,五香');
INSERT INTO `saas_shop_goods_spec` (`spec_id`, `site_id`, `goods_id`, `spec_name`, `spec_values`) VALUES (10, 0, 38, '默认', '默认');
INSERT INTO `saas_shop_goods_spec` (`spec_id`, `site_id`, `goods_id`, `spec_name`, `spec_values`) VALUES (11, 0, 39, '默认', '默认');
INSERT INTO `saas_shop_goods_spec` (`spec_id`, `site_id`, `goods_id`, `spec_name`, `spec_values`) VALUES (12, 0, 40, '网络类型', '无需合约版');
INSERT INTO `saas_shop_goods_spec` (`spec_id`, `site_id`, `goods_id`, `spec_name`, `spec_values`) VALUES (13, 0, 40, '机身颜色', '黑色,绿色,黄色,蓝色,粉色');
INSERT INTO `saas_shop_goods_spec` (`spec_id`, `site_id`, `goods_id`, `spec_name`, `spec_values`) VALUES (14, 0, 40, '套餐类型', '官方标配');
INSERT INTO `saas_shop_goods_spec` (`spec_id`, `site_id`, `goods_id`, `spec_name`, `spec_values`) VALUES (15, 0, 40, '存储容量', '128GB,256GB,512GB');
INSERT INTO `saas_shop_goods_spec` (`spec_id`, `site_id`, `goods_id`, `spec_name`, `spec_values`) VALUES (16, 0, 122, '购买方式', '标准版,移动用户特惠');
INSERT INTO `saas_shop_goods_spec` (`spec_id`, `site_id`, `goods_id`, `spec_name`, `spec_values`) VALUES (17, 0, 122, '外观', '浩瀚黑,冰河蓝');
INSERT INTO `saas_shop_goods_spec` (`spec_id`, `site_id`, `goods_id`, `spec_name`, `spec_values`) VALUES (18, 0, 122, '版本', '16GB+256GB,16GB+512GB');
INSERT INTO `saas_shop_goods_spec` (`spec_id`, `site_id`, `goods_id`, `spec_name`, `spec_values`) VALUES (19, 0, 1859, '包装', '无包装,有包装');
INSERT INTO `saas_shop_goods_spec` (`spec_id`, `site_id`, `goods_id`, `spec_name`, `spec_values`) VALUES (20, 0, 2262, '颜色', '1287B款【银针】,3128白色【银针】,3128红色【银针】,2623款【银针】,2621款【银针】,2359款【银针】,2273款【银针】,2537款【银针】,1247A款【银针】,2126款【银针】,9269A白色【银针】,9269A红色【银针】,3518白色耳钩款,3518红色耳钩款,9299款【银针】,9240款【银针】,3555金色【银针】,3555银色【银针】,3329红色【银针】,3329白色【银针】,9330B款【银针】,2383A耳钩款,2624款【银针】,3293A款【银针】');
INSERT INTO `saas_shop_goods_spec` (`spec_id`, `site_id`, `goods_id`, `spec_name`, `spec_values`) VALUES (21, 0, 2263, '颜色', '金色,银色');
INSERT INTO `saas_shop_goods_spec` (`spec_id`, `site_id`, `goods_id`, `spec_name`, `spec_values`) VALUES (22, 0, 2264, '颜色', '有耳洞！！！爱心耳针,【相思豆】耳针款,【相思豆】蚊香盘耳夹款,【相思豆】耳针款2,酒红色相思豆耳钉,几何彩色豹纹耳环耳针,珍珠花朵耳钉,爱心珍珠耳钉,圆形珍珠耳钉,红珠金边耳钉,珍珠圆圈耳钉,米白珍珠耳坠耳钩款,长款四叶草耳环,小巧双层微镶珍珠耳钉,山茶花耳钉,几何三角形耳钉,毛绒花朵耳钉,不对称花朵耳钉,金色扭曲几何三角形耳钉,微镶蝴蝶结耳钉,字母双C耳环耳针,微镶边绿宝石耳钉,金边圆形珍珠耳环,双C珍珠镶钻耳钉,交叉珍珠耳钉,多层错落耳针,相思红豆螺旋耳夹款,镶钻流苏蝴蝶结水滴珍珠耳针,花朵蝴蝶结水滴珍珠耳针,红色玛瑙小珍珠耳针,红宝石珍珠水钻【耳针】,港风复古酒红耳针,港风复古大红耳针,双圆红字宝石珍珠【耳针】,爱心水滴【红色宝石】【耳针】,威廉古堡（耳钉）,威廉古堡（蚊香盘耳夹,伊丽莎白（银针款）,伊丽莎白（软垫耳夹）,港风米色雾面耳针款,港风米色雾面蚊香盘耳夹款,不规则金耳坠【耳钉】,方形镶嵌【耳钉】,不规则红耳坠【耳钉】,【金属大红】6#菱形镶嵌【耳钉】,【金属大红】7#流苏长款耳坠【耳钉】,【金属大红】8#梅子红【耳钉】,【金属大红】13#扭曲锤纹金属【耳钉】,【金属大红】16#金属圈圈耳坠【耳钉】,【金属大红】18#珍珠方形耳坠【耳钉】,【金属大红】19#C型带坠【耳钉】,【金属大红】23#不规则三角形【耳钉】,油画感白色圆球耳夹蚊香盘耳夹款,3#莫奈花园（蚊香盘耳夹）,18#方块珍珠蓝灰（蚊香盘耳夹款）,宫廷镶钻水滴蚊香盘耳夹,摩登画廊~蚊香盘耳夹款,5#清晨白露（蚊香盘耳夹款）,41#威廉古堡（蚊香盘耳夹）,复古珍珠耳环蚊香盘耳夹  黑色,复古珍珠耳环蚊香盘耳夹  红色,玫瑰花mini小耳钉,猫眼石兔子耳针款,猫眼石兔子蚊香盘耳夹');
INSERT INTO `saas_shop_goods_spec` (`spec_id`, `site_id`, `goods_id`, `spec_name`, `spec_values`) VALUES (23, 0, 2591, '耳机型号', 'Airpods1代,Airpods2代,AirpodsPro');
INSERT INTO `saas_shop_goods_spec` (`spec_id`, `site_id`, `goods_id`, `spec_name`, `spec_values`) VALUES (24, 0, 2591, '维修项目', '单耳（无损）换新电池,双耳（无损）换新电池,双耳+电仓无痕换新电,单只麦克风维修,单只扬声器维修,双耳听筒换新网+清洁,收藏加购优先发货');
INSERT INTO `saas_shop_goods_spec` (`spec_id`, `site_id`, `goods_id`, `spec_name`, `spec_values`) VALUES (25, 0, 2591, '服务方式', '到店,邮寄服务');
INSERT INTO `saas_shop_goods_spec` (`spec_id`, `site_id`, `goods_id`, `spec_name`, `spec_values`) VALUES (26, 0, 2591, '配件类型', '原装配件');
INSERT INTO `saas_shop_goods_spec` (`spec_id`, `site_id`, `goods_id`, `spec_name`, `spec_values`) VALUES (27, 0, 2592, '耳机型号', 'Airpods1代,Airpods2代,AirpodsPro');
INSERT INTO `saas_shop_goods_spec` (`spec_id`, `site_id`, `goods_id`, `spec_name`, `spec_values`) VALUES (28, 0, 2592, '维修项目', '单耳（无损）换新电池,双耳（无损）换新电池,双耳+电仓无痕换新电,单只麦克风维修,单只扬声器维修,双耳听筒换新网+清洁,收藏加购优先发货');
INSERT INTO `saas_shop_goods_spec` (`spec_id`, `site_id`, `goods_id`, `spec_name`, `spec_values`) VALUES (29, 0, 2592, '服务方式', '到店,邮寄服务');
INSERT INTO `saas_shop_goods_spec` (`spec_id`, `site_id`, `goods_id`, `spec_name`, `spec_values`) VALUES (30, 0, 2592, '配件类型', '原装配件');
INSERT INTO `saas_shop_goods_spec` (`spec_id`, `site_id`, `goods_id`, `spec_name`, `spec_values`) VALUES (31, 0, 3217, '颜色', '黑色,白色,灰色');
INSERT INTO `saas_shop_goods_spec` (`spec_id`, `site_id`, `goods_id`, `spec_name`, `spec_values`) VALUES (32, 0, 3217, '尺码', '36-37适合35-36,38-39适合37-38,40-41适合39-40,42-43适合41-42,44-45适合43-44');
INSERT INTO `saas_shop_goods_spec` (`spec_id`, `site_id`, `goods_id`, `spec_name`, `spec_values`) VALUES (33, 0, 3218, '颜色', 'iPhone15pro,iPhone15promax,iPhone16pro,iPhone16promax');
INSERT INTO `saas_shop_goods_spec` (`spec_id`, `site_id`, `goods_id`, `spec_name`, `spec_values`) VALUES (34, 0, 3219, '颜色', '蓝宝石-钛黑,蓝宝石-钛银,蓝宝石-炫彩,蓝宝石-紫,蓝宝石-钛金,蓝宝石-钛灰');
INSERT INTO `saas_shop_goods_spec` (`spec_id`, `site_id`, `goods_id`, `spec_name`, `spec_values`) VALUES (35, 0, 3219, '大小', 'iPhone14pro/14promax,iPhone16pro/16promax/15promax');
INSERT INTO `saas_shop_goods_spec` (`spec_id`, `site_id`, `goods_id`, `spec_name`, `spec_values`) VALUES (36, 0, 3220, '颜色', '摄像头遮挡贴【黑色3个装】,手机喇叭防尘贴【20个+清洁包】');
INSERT INTO `saas_shop_goods_spec` (`spec_id`, `site_id`, `goods_id`, `spec_name`, `spec_values`) VALUES (37, 0, 3224, '颜色', '16 Pro Max,16 Pro,15Plus/16Plus,15/16,15 Pro Max,15 Pro,14 Pro Max,14Pro,13ProMax/14Plus,13/13Pro/14,12 Pro Max,12/12Pro,11ProMax/Xs Max,11/Xr,X/Xs/11Pro');
INSERT INTO `saas_shop_goods_spec` (`spec_id`, `site_id`, `goods_id`, `spec_name`, `spec_values`) VALUES (38, 0, 3225, '型号', '13/13Pro/14,13ProMax/14Plus,14Pro,14ProMax,15Pro,15/16,15Plus/16Plus,16Pro,16ProMax');
